# Site settings
title: Aksesboentu
email: egiilhamelnusa1@gmail.com
url: https://egiilhamelnusa.github.io
description: "Pada setiap kebuntuan, akan ada waktunya kita menemukan jalan keluar"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Aksesboentu

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/
  - title: facebook
    url: https://facebook.com/
  - title: stack-overflow
    url: http://stackoverflow.com/
  - title: bitbucket
    url: http://bitbucket.org/
  - title: github
    url: https://egiilhamelnusa.github.io

# Build settings
markdown: kramdown
permalink: pretty
