# Site settings
title: "Aksesboentu.id"
email: Egiilhamelnusa1@gmail.com
url: https://egiilhamelnusa.github.io
description: "Pada sebuah titik, semua buntu akan ada jalannya"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Aksesboentu.id

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:- title:
    url: https://twitter.com/Egi_Elnusa
  -title: facebook
   url: https://www.facebook.com/
  -title: github
    url: https://egiilhamelnusa.github.io/
  -title: Kampus-Belajar
    url: http://stackoverflow.com/questions/tagged/jekyll
  -title: Program studi
    url: https://sif.uin-suska.ac.id/


# Build settings
markdown: kramdown
permalink: pretty
